module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    BANNER_COLLECTION:'banner',
    WISH_COLLECTION:'wishlist',
    COUPEN_COLLECTION:'coupen'
}